// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test_plugin_service.proto

package api

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
//const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CapRequest struct {
	Input                string   `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CapRequest) Reset()         { *m = CapRequest{} }
func (m *CapRequest) String() string { return proto.CompactTextString(m) }
func (*CapRequest) ProtoMessage()    {}
func (*CapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d116d5004469a7e2, []int{0}
}

func (m *CapRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CapRequest.Unmarshal(m, b)
}
func (m *CapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CapRequest.Marshal(b, m, deterministic)
}
func (m *CapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CapRequest.Merge(m, src)
}
func (m *CapRequest) XXX_Size() int {
	return xxx_messageInfo_CapRequest.Size(m)
}
func (m *CapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CapRequest proto.InternalMessageInfo

func (m *CapRequest) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

type CapResponse struct {
	Capitilized          string   `protobuf:"bytes,1,opt,name=capitilized,proto3" json:"capitilized,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CapResponse) Reset()         { *m = CapResponse{} }
func (m *CapResponse) String() string { return proto.CompactTextString(m) }
func (*CapResponse) ProtoMessage()    {}
func (*CapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d116d5004469a7e2, []int{1}
}

func (m *CapResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CapResponse.Unmarshal(m, b)
}
func (m *CapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CapResponse.Marshal(b, m, deterministic)
}
func (m *CapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CapResponse.Merge(m, src)
}
func (m *CapResponse) XXX_Size() int {
	return xxx_messageInfo_CapResponse.Size(m)
}
func (m *CapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CapResponse proto.InternalMessageInfo

func (m *CapResponse) GetCapitilized() string {
	if m != nil {
		return m.Capitilized
	}
	return ""
}

func init() {
	proto.RegisterType((*CapRequest)(nil), "test_plugin.CapRequest")
	proto.RegisterType((*CapResponse)(nil), "test_plugin.CapResponse")
}

func init() { proto.RegisterFile("test_plugin_service.proto", fileDescriptor_d116d5004469a7e2) }

var fileDescriptor_d116d5004469a7e2 = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x49, 0x2d, 0x2e,
	0x89, 0x2f, 0xc8, 0x29, 0x4d, 0xcf, 0xcc, 0x8b, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x46, 0x92, 0x52, 0x52, 0xe2, 0xe2, 0x72, 0x4e, 0x2c,
	0x08, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe1, 0x62, 0xcd, 0xcc, 0x2b, 0x28, 0x2d,
	0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x94, 0xf4, 0xb9, 0xb8, 0xc1, 0x6a, 0x8a,
	0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x14, 0xb8, 0xb8, 0x93, 0x13, 0x0b, 0x32, 0x4b, 0x32, 0x73,
	0x32, 0xab, 0x52, 0x53, 0xa0, 0x4a, 0x91, 0x85, 0x8c, 0x02, 0xb8, 0x78, 0x83, 0x4b, 0x8a, 0x32,
	0xf3, 0xd2, 0x83, 0x21, 0x16, 0x0b, 0xd9, 0x83, 0x6d, 0x81, 0xca, 0x0b, 0x89, 0xeb, 0x21, 0xb9,
	0x40, 0x0f, 0x61, 0xbd, 0x94, 0x04, 0xa6, 0x04, 0xc4, 0x4e, 0x27, 0xab, 0x28, 0x8b, 0xf4, 0xcc,
	0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0xfd, 0xe4, 0xfc, 0xbc, 0x92, 0xc4, 0xcc, 0xbc,
	0xd4, 0xa2, 0x14, 0x64, 0x26, 0x44, 0x5b, 0xb1, 0x3e, 0xc8, 0x0c, 0x5d, 0x08, 0x47, 0x3f, 0xb1,
	0x20, 0x33, 0x89, 0x0d, 0xec, 0x6d, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x59, 0xba, 0x33,
	0x75, 0x13, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StringServiceClient is the client API for StringService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StringServiceClient interface {
	Capitilize(ctx context.Context, in *CapRequest, opts ...grpc.CallOption) (*CapResponse, error)
}

type stringServiceClient struct {
	cc *grpc.ClientConn
}

func NewStringServiceClient(cc *grpc.ClientConn) StringServiceClient {
	return &stringServiceClient{cc}
}

func (c *stringServiceClient) Capitilize(ctx context.Context, in *CapRequest, opts ...grpc.CallOption) (*CapResponse, error) {
	out := new(CapResponse)
	err := c.cc.Invoke(ctx, "/test_plugin.StringService/Capitilize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StringServiceServer is the server API for StringService service.
type StringServiceServer interface {
	Capitilize(context.Context, *CapRequest) (*CapResponse, error)
}

// UnimplementedStringServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStringServiceServer struct {
}

func (*UnimplementedStringServiceServer) Capitilize(ctx context.Context, req *CapRequest) (*CapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Capitilize not implemented")
}

func RegisterStringServiceServer(s *grpc.Server, srv StringServiceServer) {
	s.RegisterService(&_StringService_serviceDesc, srv)
}

func _StringService_Capitilize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StringServiceServer).Capitilize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/test_plugin.StringService/Capitilize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StringServiceServer).Capitilize(ctx, req.(*CapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StringService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "test_plugin.StringService",
	HandlerType: (*StringServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Capitilize",
			Handler:    _StringService_Capitilize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test_plugin_service.proto",
}
