// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test-plugin3.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
//const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateContainerRequest struct {
	ApplicationName      string   `protobuf:"bytes,1,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	FileLocation         string   `protobuf:"bytes,2,opt,name=file_location,json=fileLocation,proto3" json:"file_location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateContainerRequest) Reset()         { *m = CreateContainerRequest{} }
func (m *CreateContainerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateContainerRequest) ProtoMessage()    {}
func (*CreateContainerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_644da1be534b9232, []int{0}
}

func (m *CreateContainerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateContainerRequest.Unmarshal(m, b)
}
func (m *CreateContainerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateContainerRequest.Marshal(b, m, deterministic)
}
func (m *CreateContainerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateContainerRequest.Merge(m, src)
}
func (m *CreateContainerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateContainerRequest.Size(m)
}
func (m *CreateContainerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateContainerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateContainerRequest proto.InternalMessageInfo

func (m *CreateContainerRequest) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

func (m *CreateContainerRequest) GetFileLocation() string {
	if m != nil {
		return m.FileLocation
	}
	return ""
}

type CreateContainerResponse struct {
	ContainerId          string   `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateContainerResponse) Reset()         { *m = CreateContainerResponse{} }
func (m *CreateContainerResponse) String() string { return proto.CompactTextString(m) }
func (*CreateContainerResponse) ProtoMessage()    {}
func (*CreateContainerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_644da1be534b9232, []int{1}
}

func (m *CreateContainerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateContainerResponse.Unmarshal(m, b)
}
func (m *CreateContainerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateContainerResponse.Marshal(b, m, deterministic)
}
func (m *CreateContainerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateContainerResponse.Merge(m, src)
}
func (m *CreateContainerResponse) XXX_Size() int {
	return xxx_messageInfo_CreateContainerResponse.Size(m)
}
func (m *CreateContainerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateContainerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateContainerResponse proto.InternalMessageInfo

func (m *CreateContainerResponse) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateContainerRequest)(nil), "test_plugin3.CreateContainerRequest")
	proto.RegisterType((*CreateContainerResponse)(nil), "test_plugin3.CreateContainerResponse")
}

func init() { proto.RegisterFile("test-plugin3.proto", fileDescriptor_644da1be534b9232) }

var fileDescriptor_644da1be534b9232 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0xd0, 0xbf, 0x4b, 0xc3, 0x50,
	0x10, 0x07, 0x70, 0xea, 0x20, 0x78, 0x46, 0x2a, 0x37, 0x68, 0x71, 0xd2, 0xaa, 0xa0, 0x83, 0x09,
	0xd8, 0x49, 0x74, 0xb2, 0x93, 0x22, 0x0e, 0x71, 0x73, 0x30, 0x5c, 0x93, 0xb3, 0x3d, 0x48, 0xde,
	0x7b, 0xe6, 0xdd, 0xeb, 0xdf, 0x2f, 0x6d, 0x62, 0x79, 0xa8, 0xd0, 0xed, 0xf8, 0x70, 0xdc, 0x8f,
	0x2f, 0xa0, 0xb2, 0xd7, 0x1b, 0x57, 0x87, 0xb9, 0x98, 0x49, 0xea, 0x5a, 0xab, 0x16, 0x93, 0x95,
	0x15, 0xbd, 0x8d, 0x17, 0x70, 0x34, 0x6d, 0x99, 0x94, 0xa7, 0xd6, 0x28, 0x89, 0xe1, 0x36, 0xe7,
	0xaf, 0xc0, 0x5e, 0xf1, 0x1a, 0x0e, 0xc9, 0xb9, 0x5a, 0x4a, 0x52, 0xb1, 0xa6, 0x30, 0xd4, 0xf0,
	0x68, 0x70, 0x3a, 0xb8, 0xda, 0xcb, 0x87, 0x91, 0xbf, 0x52, 0xc3, 0x78, 0x0e, 0x07, 0x9f, 0x52,
	0x73, 0x51, 0xdb, 0x0e, 0x47, 0x3b, 0xeb, 0xbe, 0x64, 0x85, 0x2f, 0xbd, 0x8d, 0x1f, 0xe0, 0xf8,
	0xcf, 0x26, 0xef, 0xac, 0xf1, 0x8c, 0x67, 0x90, 0x94, 0x3f, 0x58, 0x48, 0xd5, 0xaf, 0xd9, 0xdf,
	0xd8, 0x53, 0x75, 0xab, 0x80, 0xcf, 0xb4, 0xa4, 0x3c, 0x18, 0x95, 0x86, 0xdf, 0xb8, 0x5d, 0x4a,
	0xc9, 0xf8, 0x01, 0xc3, 0x5f, 0x33, 0xf1, 0x22, 0x8d, 0xff, 0x4b, 0xff, 0x7f, 0xee, 0xe4, 0x72,
	0x4b, 0x57, 0x77, 0xd8, 0xe3, 0xfd, 0xfb, 0xdd, 0x5c, 0x74, 0x11, 0x66, 0x69, 0x69, 0x9b, 0x6c,
	0x73, 0x4f, 0x15, 0x97, 0xdd, 0x0c, 0x9f, 0xc5, 0x51, 0x67, 0xe4, 0x64, 0xb6, 0xbb, 0xce, 0x7b,
	0xf2, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xa3, 0x2a, 0x99, 0xe6, 0x85, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JavaRuntimeServiceClient is the client API for JavaRuntimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JavaRuntimeServiceClient interface {
	CreateContainer(ctx context.Context, in *CreateContainerRequest, opts ...grpc.CallOption) (*CreateContainerResponse, error)
}

type javaRuntimeServiceClient struct {
	cc *grpc.ClientConn
}

func NewJavaRuntimeServiceClient(cc *grpc.ClientConn) JavaRuntimeServiceClient {
	return &javaRuntimeServiceClient{cc}
}

func (c *javaRuntimeServiceClient) CreateContainer(ctx context.Context, in *CreateContainerRequest, opts ...grpc.CallOption) (*CreateContainerResponse, error) {
	out := new(CreateContainerResponse)
	err := c.cc.Invoke(ctx, "/test_plugin3.JavaRuntimeService/CreateContainer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JavaRuntimeServiceServer is the server API for JavaRuntimeService service.
type JavaRuntimeServiceServer interface {
	CreateContainer(context.Context, *CreateContainerRequest) (*CreateContainerResponse, error)
}

// UnimplementedJavaRuntimeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedJavaRuntimeServiceServer struct {
}

func (*UnimplementedJavaRuntimeServiceServer) CreateContainer(ctx context.Context, req *CreateContainerRequest) (*CreateContainerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateContainer not implemented")
}

func RegisterJavaRuntimeServiceServer(s *grpc.Server, srv JavaRuntimeServiceServer) {
	s.RegisterService(&_JavaRuntimeService_serviceDesc, srv)
}

func _JavaRuntimeService_CreateContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JavaRuntimeServiceServer).CreateContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/test_plugin3.JavaRuntimeService/CreateContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JavaRuntimeServiceServer).CreateContainer(ctx, req.(*CreateContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JavaRuntimeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "test_plugin3.JavaRuntimeService",
	HandlerType: (*JavaRuntimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateContainer",
			Handler:    _JavaRuntimeService_CreateContainer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test-plugin3.proto",
}
